# Generated by Django 4.2 on 2024-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idTrip', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
