# Generated by Django 4.2 on 2024-01-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
